#!/usr/bin/env bash
if which javac
  then echo "jdk installed"
  else
  sudo apt-get install default-jre
  sudo apt-get install default-jdk
fi

echo "Compiling"
./compile_all.sh

cat input.txt | java -cp bin Dom
